In [52]:
import numpy as np
import matplotlib.pyplot as plt


In [53]:
X = np.array([[0.1,2,3,4,5,6,7],[0.1,2,3,4,5,6,7]])
Y = np.array([[0,0,0,0,1,1,1]])
print(X.shape)
one = np.ones((X.shape[1], 1))
X = np.array(X).T
X = np.concatenate((one,X),axis=1)
Y = np.array(Y).T

# test 
print(X)
W = np.array([[1,1,2]]).T
print(W)
c = np.dot(X,W)
print(c)

(2, 7)
[[1.  0.1 0.1]
 [1.  2.  2. ]
 [1.  3.  3. ]
 [1.  4.  4. ]
 [1.  5.  5. ]
 [1.  6.  6. ]
 [1.  7.  7. ]]
[[1]
 [1]
 [2]]
[[ 1.3]
 [ 7. ]
 [10. ]
 [13. ]
 [16. ]
 [19. ]
 [22. ]]


In [54]:
# step 1: initialize and forward propagate  
# f(x) = w_1 * x + w_0
# g(x) = 1/(1+e^f(x))
def f(x):
    return np.dot(x,W) 

print(f(X[1])) 
print(len(X))

[7.]
7


In [55]:
# activate function 
def act(x):
    u = f(x)
    return 1/(1+np.exp(-u))
print(act(X[0]))

[0.78583498]


In [56]:
# step 2: loss function 
def loss():
    sum = 0
    for i in range(len(X)):
        sum += (act(X[i])-Y[i])**2
    return sum/(2*len(X)) 
print(loss())

[0.25825857]


In [64]:
# step 3: Differentiation
def derivate(k):
    sum = 0
    for i in range(len(X)):
        d1 = 2*(act(X[i])-Y[i])
        u = f(X[i])
        fu = 1/(1+np.exp(-u))
        d2 = fu*(1-fu)
        d3 = X[i][k]
        sum = sum + d1*d2*d3
    return sum/(2*len(X))

print(derivate(2))

[0.00092551]


In [63]:
# step 3: Differentiation
def derivate_other(k):
    sum = 0
    for i in range(len(X)):
        sum = sum + (act(X[i])-Y[i])
    return sum/(2*len(X))

print(derivate_other(2))

[0.28029584]


In [65]:
# step 4: update weight 
epoch = 50
learning_rate = 0.001
epsilon = 0.0001
W = np.array([[1,3,12]]).T
for iter in range(epoch):
    before_loss = loss()
    print(iter,': ',before_loss) 
    for i in range(len(W)):
        W[i] = W[i] - learning_rate*derivate(i)
    if before_loss-loss() < epsilon:
        break 
print(loss())
# print result 
print(W)
    

0 :  [0.27528844]
1 :  [0.25839547]
2 :  [0.25449216]
3 :  [0.25038923]
4 :  [0.24829033]
5 :  [0.24617666]
6 :  [0.24406141]
7 :  [0.24195459]
8 :  [0.23983884]
9 :  [0.23748472]
10 :  [0.23293277]
11 :  [0.20880049]
12 :  [0.125]
[0.125]
[[0]
 [0]
 [0]]
